/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRIMEFIB_H_RPCGEN
#define _PRIMEFIB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct output {
	int v;
	float t;
};
typedef struct output output;

#define ADD_PROG 0x20000001
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define prime 1
extern  output * prime_1(int *, CLIENT *);
extern  output * prime_1_svc(int *, struct svc_req *);
#define fibonacci 2
extern  output * fibonacci_1(int *, CLIENT *);
extern  output * fibonacci_1_svc(int *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define prime 1
extern  output * prime_1();
extern  output * prime_1_svc();
#define fibonacci 2
extern  output * fibonacci_1();
extern  output * fibonacci_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_output (XDR *, output*);

#else /* K&R C */
extern bool_t xdr_output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRIMEFIB_H_RPCGEN */
