###########################################################
#
# Simple Makefile for Advanced Operating Systems Project 4
#
###########################################################
.SUFFIXES: .h .c .cpp .l .o

aosproj4: aosproj4.cpp
	mpicxx aosproj4.cpp -o aosproj4

clean:
	/bin/rm -f *.o *~ core aosproj4
