###########################################################
#
# Simple Makefile for Operating Systems Project 4
# banker's algorithm
#
###########################################################
.SUFFIXES: .h .c .cpp .l .o

banker: banker.c
	gcc banker.c -o banker

clean:
	/bin/rm -f *.o *~ core banker



