/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpctime.h"

bool_t
xdr_twoArgs (XDR *xdrs, twoArgs *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tenArgs (XDR *xdrs, tenArgs *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->arg_1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg_2))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg_3))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg_4))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg_5))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg_6))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg_7))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg_8))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg_9))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg_10))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_arrayArg (XDR *xdrs, arrayArg *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, ( 100 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->a, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->a;
					i < 100; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, ( 100 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->a, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->a;
					i < 100; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->a, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
