/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCTIME_H_RPCGEN
#define _RPCTIME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct twoArgs {
	int arg1;
	float arg2;
};
typedef struct twoArgs twoArgs;

struct tenArgs {
	double arg_1;
	double arg_2;
	double arg_3;
	double arg_4;
	double arg_5;
	double arg_6;
	double arg_7;
	double arg_8;
	double arg_9;
	double arg_10;
};
typedef struct tenArgs tenArgs;

struct arrayArg {
	int a[100];
};
typedef struct arrayArg arrayArg;

#define ADD_PROG 0x20000002
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define nullRemote1 1
extern  void * nullremote1_1(void *, CLIENT *);
extern  void * nullremote1_1_svc(void *, struct svc_req *);
#define nullRemote2 2
extern  int * nullremote2_1(int *, CLIENT *);
extern  int * nullremote2_1_svc(int *, struct svc_req *);
#define nullRemote3 3
extern  twoArgs * nullremote3_1(twoArgs *, CLIENT *);
extern  twoArgs * nullremote3_1_svc(twoArgs *, struct svc_req *);
#define nullRemote4 4
extern  tenArgs * nullremote4_1(tenArgs *, CLIENT *);
extern  tenArgs * nullremote4_1_svc(tenArgs *, struct svc_req *);
#define nullRemote5 5
extern  arrayArg * nullremote5_1(arrayArg *, CLIENT *);
extern  arrayArg * nullremote5_1_svc(arrayArg *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define nullRemote1 1
extern  void * nullremote1_1();
extern  void * nullremote1_1_svc();
#define nullRemote2 2
extern  int * nullremote2_1();
extern  int * nullremote2_1_svc();
#define nullRemote3 3
extern  twoArgs * nullremote3_1();
extern  twoArgs * nullremote3_1_svc();
#define nullRemote4 4
extern  tenArgs * nullremote4_1();
extern  tenArgs * nullremote4_1_svc();
#define nullRemote5 5
extern  arrayArg * nullremote5_1();
extern  arrayArg * nullremote5_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_twoArgs (XDR *, twoArgs*);
extern  bool_t xdr_tenArgs (XDR *, tenArgs*);
extern  bool_t xdr_arrayArg (XDR *, arrayArg*);

#else /* K&R C */
extern bool_t xdr_twoArgs ();
extern bool_t xdr_tenArgs ();
extern bool_t xdr_arrayArg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCTIME_H_RPCGEN */
